### ISSUE TITLE
Ideas / TODO

### ISSUE THREAD

**Issue by IllusionTheDev** [IllusionTheDev/SkyblockCore#1]
I'd appreciate if everyone that read this could contribute an idea to implement in the future.

- Implement commands
- Expansion system
- In-game configuration
- Better API documentation
- Comment and doc

**Comment by IllusionTheDev** [comment]
For commands, the ideas are the following:

ADMIN COMMANDS:

- /is admin reset <player> - Resets all player data
- /is admin purge <type> <amount>

    types:
   -> time-played, as in time that the player has progressed
   -> last-login, as in last time a player logged in
   -> all, to purge all islands
   
- /is admin checkdata <player> - lists player data (money, xp, items)

**Comment by IllusionTheDev** [comment]
- Zstd compression for all files
- RabbitMQ support, for messaging
- Redis pool management, as the pool can run out of resources
- Command Tab Completion
- SlimeWorldManager support (Maybe?)

**Comment by IllusionTheDev** [comment]
- Database creation / Backup files using a proprietary file extension
- Database conversion
- Void world as a hub for worlds being loaded
- Exception logging, ideally with a file, full stack trace and additional information

**Comment by Rabbit0w0** [comment]
> For commands, the ideas are the following:
> 
> ADMIN COMMANDS:
> 
> * /is admin reset  - Resets all player data
> * /is admin purge  
>   types:
>   -> time-played, as in time that the player has progressed
>   -> last-login, as in last time a player logged in
>   -> all, to purge all islands
> * /is admin checkdata  - lists player data (money, xp, items)

If the server is in BungeeCord mode, the admin commands should be on the BungeeCord-side. Then send a message through RabbitMQ.

**Comment by IllusionTheDev** [comment]
> > For commands, the ideas are the following:
> > ADMIN COMMANDS:
> > 
> > * /is admin reset  - Resets all player data
> > * /is admin purge
> >   types:
> >   -> time-played, as in time that the player has progressed
> >   -> last-login, as in last time a player logged in
> >   -> all, to purge all islands
> > * /is admin checkdata  - lists player data (money, xp, items)
> 
> If the server is in BungeeCord mode, the admin commands should be on the BungeeCord-side. Then send a message through RabbitMQ.

Commands will be run on the spigot side, because not all networks are skyblock-specific.

All commands support bungee forwarding (there's a fancy packet system for that). The only skyblock-specific bungee command is `/skyblock`, which pairs you up to the ideal island server and sends you there.

I might make a SkyblockCommands jar that will allow you to use Skyblock commands on the proxy, under specific servers.

**Comment by IllusionTheDev** [comment]
I am going to close this issue as the plugin has been undergoing a massive rewrite. A new todo list will be made soon.
