### ISSUE TITLE
Suggestion: Add the possibility of having more than 1 island.

### ISSUE THREAD

**Issue by Zarkness** [IllusionTheDev/SkyblockCore#4]
I do not know if it will be possible, but my suggestion is to add the possibility of having multiple islands and that with the command /is select will open a menu where the islands that you have created or putting /is select 2 you select the island 2 and that putting /is go will send you to the selected island which in this case would be the island 2 and to have more islands you would need to have a permit which would be skyblockcore.islands.3 to have 3 islands.

Another thing is there any discord group to be aware of updates?

**Comment by IllusionTheDev** [comment]
My biggest problem with implementing the multiple island system is that servers have a limited island capacity.

By default, each server supports 25 loaded islands at a time. An island world is only released ~12 seconds after the player leaves, to make sure it is properly saved and the world doesn't corrupt (reloading worlds too fast can cause corruption).

What if all 25 islands are fully loaded, and the player wants to switch to a secondary island? The player would have to be transferred to another server or wait 12 seconds on a temporary world.

Let's say the player is transferred to another server: How can we guarantee that that other server has the capacity? What if this isn't a MySQL/MongoDB setup that supports multiple servers? That's where things get messy.

--

Development is slow, I have a temporary discord server up but there's no big reason to use it, at this early stage of development.

**Comment by Zarkness** [comment]
Wow, I had not thought that the world could be corrupted, there must be some way, the only thing I can think of is a profile system like hypixel has.

---------
and about the discord group, then I will wait until I have a definitive one and not a temporary one.

**Comment by Zarkness** [comment]
@IllusionTheDev I have seen that in the wiki you say that you can be helped by testing the plugin and I would like to help you in that way.

**Comment by IllusionTheDev** [comment]
Hey, I've made a basic discord server (accessible [here](https://discord.gg/ZpEk9vdRj9)) where you can join and discuss everything regarding the plugin.

I'll be dropping a few test jars throughout the development process, which people will be able to test.
