### ISSUE TITLE
Compile Latest Build

### ISSUE THREAD

**Issue by iamlexivale** [IllusionTheDev/SkyblockCore#7]
Hi, i love this SkyblockCore concept, and I would to be Testing, Helping with the wiki, Writing issue, Planning and also Donating. But idk how to automatic compile latest build. will you build a CI/CD to always create latest build?

i plan to setup network mode so plugin install in bungee latest version and spigot 1.8, also I used SlimeWorldManager for World Management.

I also recommend to create community based Discord or anything else, I you had no time I can help you to create Discord community.

Thanks,
Lexivale

**Comment by IllusionTheDev** [comment]
There is an already existing pipeline for this project, but it seems to have some compilation issues that I don't have on my IDE. (Has to do with supporting 2 entirely different versions of worldedit) 

Thanks for showing interest in the project! I have made a basic discord server accessible [here](https://discord.gg/ZpEk9vdRj9).

**Comment by IllusionTheDev** [comment]
I've added some missing files that allow people to compile the latest version of the project.
